include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_positional_boolean_parameters
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - sort_constructors_first
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_await_in_return
    - use_super_parameters