name: iterable_extensions
description: A comprehensive collection of useful extension methods for Dart's Iterable class, providing null-safe operations, collection utilities, and functional programming helpers.
version: 1.0.0
homepage: https://github.com/thefuzzybear/iterable_extensions
repository: https://github.com/thefuzzybear/iterable_extensions
issue_tracker: https://github.com/thefuzzybear/iterable_extensions/issues
documentation: https://pub.dev/documentation/iterable_extensions/latest/

topics:
  - extensions
  - collections
  - utilities
  - functional-programming
  - null-safety

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0


